
version: '3'

services:

    # web server
    # https://hub.docker.com/_/nginx
    nginx:
        container_name: ${SERVER_CONTAINER_NAME}
        image: nginx:latest
        volumes:
            # - './nginx:/etc/nginx/conf.d'
            - './nginx:/etc/nginx/templates'
            - './src:${APP_ROOT}'
            # - './logs/nginx:/var/log/nginx'
        ports:
            - '${APP_PORT}:80'
        environment:
            - TZ=${TIMEZONE}
            - PHP_CONTAINER_NAME=${PHP_CONTAINER_NAME}
            - SERVER_PORT=${APP_PORT}
            - SERVER_NAME=${HOSTNAME}
            - DOCUMENT_ROOT=${DOCUMENT_ROOT}
        networks:
            - ${NETWORK}

    # php
    # https://hub.docker.com/_/php
    php:
        container_name: ${PHP_CONTAINER_NAME}
        build: ./php
        volumes:
            - './src:${APP_ROOT}'
            - './php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-debug.ini'
            - './php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
            # - './logs/laravel:/var/www/src/storage/logs'
        ports:
            - 9000:9000
        environment:
            - TZ=${TIMEZONE}
            - APP_ROOT=${APP_ROOT}
        networks:
            - ${NETWORK}

    # mysql
    # https://hub.docker.com/_/mysql
    mysql:
        container_name: ${MYSQL_CONTAINER_NAME}
        image: mysql:latest
        volumes:
            - './mysql:${MYSQL_PATH}'
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            - TZ=${TIMEZONE}
            - MYSQL_DATABASE=${MYSQL_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - ${NETWORK}

    # postgresql
    # https://hub.docker.com/_/postgres
    postgresql:
        container_name: ${POSTGRESQL_CONTAINER_NAME}
        image: postgres:latest
        restart: always
        volumes:
            - './postgresql:${POSTGRES_PATH}'
            # logs
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - TZ=${TIMEZONE}
            - POSTGRES_DB=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - PGDATA=${POSTGRES_PATH}
        networks:
            - ${NETWORK}

    # db gui
    # https://hub.docker.com/_/adminer
    database-admin:
        container_name: ${DB_ADMIN_CONTAINER_NAME}
        image: adminer:latest
        ports:
            - ${DB_ADMIN_PORT}:8080
        environment:
            - TZ=${TIMEZONE}
            # - ADMINER_DEFAULT_SERVER=${MYSQL_CONTAINER_NAME}-OR-${POSTGRESQL_CONTAINER_NAME}
        networks:
            - ${NETWORK}

networks:
    project-network:
